CREATE TABLE IF NOT EXISTS events (
  id                          INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at                  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  ip_hash                     TEXT    NOT NULL,
  plugin_version              TEXT    NOT NULL,
  device_id                   TEXT    NOT NULL,
  outcome                     TEXT    NOT NULL,
  file_ext                    TEXT    NOT NULL,
  language                    TEXT    NOT NULL,
  prefix_length               INTEGER NOT NULL,
  trimmed_prefix_length       INTEGER NOT NULL,
  line_count                  INTEGER NOT NULL,
  relative_position           REAL    NOT NULL,
  after_cursor_ws             INTEGER NOT NULL,
  last_char                   TEXT    NOT NULL DEFAULT '',
  last_nonws_char             TEXT    NOT NULL DEFAULT '',
  indentation_level           INTEGER NOT NULL,
  prev_filter_shown           INTEGER NOT NULL,
  filter_score                REAL    NOT NULL,
  completion_lines            INTEGER NOT NULL,
  completion_additions        INTEGER NOT NULL,
  completion_deletions        INTEGER NOT NULL,
  completion_source           TEXT    NOT NULL,
  manually_triggered          INTEGER NOT NULL,
  provider                    TEXT    NOT NULL,
  stage_index                 INTEGER NOT NULL DEFAULT 0,
  cursor_target_distance      INTEGER NOT NULL DEFAULT 0,
  is_prefetched               INTEGER NOT NULL DEFAULT 0,
  display_duration_ms         INTEGER NOT NULL,
  time_since_last_decision_ms INTEGER NOT NULL,
  time_since_last_edit_ms     INTEGER NOT NULL,
  typing_speed                REAL    NOT NULL,
  recent_actions              TEXT    NOT NULL,
  has_diagnostics             INTEGER NOT NULL,
  treesitter_scope            TEXT    NOT NULL,
  edit_count                  INTEGER NOT NULL,
  predicted_edit_ratio        REAL    NOT NULL,
  completions_since_accept    INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_device_id ON events(device_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
CREATE INDEX IF NOT EXISTS idx_events_outcome ON events(outcome);
